//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveCode
    {
        public int ActiveCodeID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ActCode { get; set; }
        public Nullable<System.DateTime> ExpireOn { get; set; }
        public bool Status { get; set; }
        public ActiveCode(){}
        public ActiveCode(int MemberID, string ActCode, DateTime ExpireOn, bool Status)
        {
            this.MemberID = MemberID;
            this.ActCode = ActCode;
            this.ExpireOn = ExpireOn;
            this.Status = Status;
        }
        public virtual Member Member { get; set; }
    }
}
