//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleID { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Content { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ShortDes { get; set; }
        public string Image { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual Member Member { get; set; }
    }
}
