//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KoiParent
    {
        public int id { get; set; }
        public Nullable<int> OffspringID { get; set; }
        public Nullable<int> KoiSonID { get; set; }
        public string IsMomorDad { get; set; }
    
        public virtual Koi Koi { get; set; }
        public virtual OffSpringOf OffSpringOf { get; set; }
    }
}
