//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int MediaID { get; set; }
        public string LinkImage { get; set; }
        public string LinkVideo { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string ModelTypeID { get; set; }
    
        public virtual InfoDetail InfoDetail { get; set; }
        public virtual KoiFarm KoiFarm { get; set; }
        public virtual ModelType ModelType { get; set; }
    }
}
