//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Comments = new HashSet<Comment>();
            this.KoiFarms = new HashSet<KoiFarm>();
            this.Owners = new HashSet<Owner>();
        }
    
        public int MemberID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Image { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<KoiFarm> KoiFarms { get; set; }
        public virtual ICollection<Owner> Owners { get; set; }
    }
}
