//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public string Title { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Content { get; set; }
        public Nullable<int> ReplyID { get; set; }
        public bool IsRead { get; set; }
        public bool Status { get; set; }
        public Message() { }

        public Message(string Title, DateTime Datetime, int? SenderID, int? MemberID, string Content, int? ReplyID, bool IsRead,
            bool Status)
        {
            this.Title = Title;
            this.Datetime = Datetime;
            this.SenderID = SenderID;
            this.MemberID = MemberID;
            this.Content = Content;
            this.ReplyID = ReplyID;
            this.IsRead = IsRead;
            this.Status = Status;
        }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
