//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NoID { get; set; }
        public int MemberID { get; set; }
        public int SenderID { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public System.DateTime Datetime { get; set; }
        public string url { get; set; }
        public string Content { get; set; }
        public bool isRead { get; set; }
        public bool status { get; set; }
        public Notification()
        {
        }
        public Notification(int MemberID, int SenderID, int? ObjectType, int? ObjectID, DateTime Datetime, string Content, string url, bool isRead, bool status)
        {
            this.MemberID = MemberID;
            this.SenderID = SenderID;
            this.ObjectType = ObjectType;
            this.ObjectID = ObjectID;
            this.Datetime = Datetime;
            this.url = url;
            this.Content = Content;
            this.isRead = isRead;
            this.status = status;
        }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
