//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffSpringOf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OffSpringOf()
        {
            this.KoiParents = new HashSet<KoiParent>();
        }
    
        public int OffspringID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> KoiID { get; set; }
    
        public virtual Koi Koi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KoiParent> KoiParents { get; set; }
    }
}
