//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int RateID { get; set; }
        public int RateSocre { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> AnswerID { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Member Member { get; set; }
        public virtual Question Question { get; set; }
    }
}
