//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public string Content { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ModelTypeID { get; set; }
        public Nullable<int> ModelId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Koi Koi { get; set; }
        public virtual KoiFarm KoiFarm { get; set; }
        public virtual ModelType ModelType { get; set; }
        public virtual Question Question { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
