//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoiManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public string Content { get; set; }
        public Nullable<int> MemberID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public bool Status { get; set; }
        public virtual Member Member { get; set; }
    }
}
