//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KoiFarm
    {
        public KoiFarm()
        {
            this.Comments = new HashSet<Comment>();
            this.Owners = new HashSet<Owner>();
        }
    
        public int KoifarmID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string FarmName { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<Owner> Owners { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
