//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Comments = new HashSet<Comment>();
            this.KoiFarms = new HashSet<KoiFarm>();
            this.KoiFarms1 = new HashSet<KoiFarm>();
            this.Owners = new HashSet<Owner>();
        }

        public Member( string Name, string UserName, string Password, DateTime? dob, string Image, string Gender, string Phone, string Email, string Addres, bool Status)
        {
            this.Comments = new HashSet<Comment>();
            this.KoiFarms = new HashSet<KoiFarm>();
            this.KoiFarms1 = new HashSet<KoiFarm>();
            this.Owners = new HashSet<Owner>();
            this.Name = Name;
            this.UserName = UserName;
            this.Password = Password;
            this.Dob = dob;
            this.Image = Image;
            this.Gender = Gender;
            this.Phone = Phone;
            this.Email = Email;
            this.Address = Address;
            this.Status = Status;
        }

        public int MemberID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Image { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<KoiFarm> KoiFarms { get; set; }
        public virtual ICollection<KoiFarm> KoiFarms1 { get; set; }
        public virtual ICollection<Owner> Owners { get; set; }
    }
}
